@startuml

title ユースケース

left to right direction
skinparam actorStyle awesome

usecase ユーザーをフォローする #cccccc
usecase ユーザーを検索する #cccccc
usecase ユーザーのツイートを見る #cccccc

ゲストユーザー -|> ユーザー
ログインユーザー -|> ユーザー

ユーザー -- (ユーザーを検索する)
ゲストユーザー -- (アカウントを作成する)
ゲストユーザー -- (ログインする)
ログインユーザー -- (ツイートをする)
ログインユーザー -- (ツイートを消す)
ログインユーザー -- (ユーザーをフォローする)
ログインユーザー -- (ツイート一覧を見る)

(ユーザーを検索する) ..> (ユーザーのツイートを見る) : 発生
(アカウントを作成する) ..> (ログインする) : 発生
(ツイートをする) ..> (ログインする) : 先行
(ツイートを消す) ..> (ツイートをする) : 先行
(ユーザーをフォローする) ..> (ログインする) : 先行
(ツイート一覧を見る) ..> (ログインする) : 先行

@enduml


@startuml

title ロバストネス分析

left to right direction
skinparam actorStyle awesome

actor ユーザー
actor ゲストユーザー
actor ログインユーザー
ゲストユーザー -|> ユーザー
ログインユーザー -|> ユーザー

boundary アカウント作成画面
boundary ログイン画面
boundary ホーム画面
boundary ユーザー検索画面 #cccccc
boundary ユーザー検索結果画面 #cccccc
boundary ユーザー画面 #cccccc

entity アカウント
entity ツイート
entity フォロー #cccccc

ゲストユーザー --> アカウント作成画面
ゲストユーザー --> ログイン画面
ログインユーザー --> ユーザー検索結果画面
ログインユーザー --> ホーム画面
ユーザー --> ユーザー検索画面
ユーザー --> ユーザー検索結果画面

package uc:アカウントを作成する {
  control アカウントを作成する
  control セッション情報を作成する

  アカウント作成画面 --> アカウントを作成する : アカウント情報を入れる
  アカウントを作成する -- アカウント
  アカウントを作成する --> セッション情報を作成する
  セッション情報を作成する --> ホーム画面
}

package uc:ログインする {
  control ユーザー認証する
  control セッション情報を作成する

  ログイン画面 --> ユーザー認証する : アカウント名とパスワードを入れる
  ユーザー認証する -- アカウント
  ユーザー認証する --> セッション情報を作成する : 認証成功
}

package uc:ユーザーを検索する #cccccc {
  control アカウント名を検索する #cccccc

  ユーザー検索画面 --> アカウント名を検索する : キーワードを入れる
  アカウント名を検索する -- アカウント
  アカウント名を検索する --> ユーザー検索結果画面
}

package uc:ユーザーのツイートを見る #cccccc {
  control ユーザーの情報を取得する #cccccc
  control ユーザーのツイートを検索する #cccccc

  ユーザー検索結果画面 --> ユーザーの情報を取得する : ユーザーを選択する
  ユーザーの情報を取得する -- アカウント
  ユーザーの情報を取得する --> ユーザーのツイートを検索する
  ユーザーのツイートを検索する -- ツイート
  ユーザーのツイートを検索する --> ユーザー画面
}

package uc:ユーザーをフォローする #cccccc {
  control フォローを作成する #cccccc

  ユーザー検索結果画面 --> フォローを作成する : フォローボタンを押す
  フォローを作成する -- フォロー
}

package uc:ツイートをする {
  control ツイートを作成する

  ホーム画面 --> ツイートを作成する : ツイートを書く
  ツイートを作成する -- ツイート
}

package uc:ツイートを削除する {
  control ツイートを削除する

  ホーム画面 --> ツイートを削除する : ツイートの削除ボタンを書く
  ツイートを削除する -- ツイート
}

package uc:ツイート一覧を見る {
  control フォローユーザーを取得する #cccccc
  control 自分とフォローユーザーのツイートを取得する

  ホーム画面 --> フォローユーザーを取得する
  フォローユーザーを取得する -- フォロー
  フォローユーザーを取得する --> 自分とフォローユーザーのツイートを取得する
  自分とフォローユーザーのツイートを取得する -- ツイート
  自分とフォローユーザーのツイートを取得する --> ホーム画面
}

@enduml


@startuml

title ドメインモデル

skinparam actorStyle awesome

object アカウント
object フォロー #cccccc
object ツイート

アカウント o--- "0..*" フォロー
アカウント o--- "0..*" ツイート

@enduml
